---
title: "Fig_1"
author: "Cheryl Logan"
date: "3/26/2018"
output: html_document
---
## Load libraries
```{r load libraries, echo = FALSE, message = FALSE, warning = FALSE}
library(tidyverse) #install.packages("tidyverse")
library(skimr) #install.packages("skimr")
library(ggthemes) #install.packages("ggthemes")
library(reshape2)
```

## Load data
```{r load data, echo = FALSE, message = FALSE, warning = FALSE}
## data
rcp26 <- read_csv("~/github/coral_model/healthy_rcp26.csv") 
rcp45 <- read_csv("~/github/coral_model/healthy_rcp45.csv") 
rcp60 <- read_csv("~/github/coral_model/healthy_rcp60.csv") 
rcp85 <- read_csv("~/github/coral_model/healthy_rcp85.csv") 
```

# Append rcp column
```{r append rcp column, echo = FALSE, message = FALSE, warning = FALSE}
rcp26 <- mutate(rcp26,rcp = "RCP2.6")
rcp45 <- mutate(rcp45,rcp = "RCP4.5")
rcp60 <- mutate(rcp60,rcp = "RCP6.0")
rcp85 <- mutate(rcp85,rcp = "RCP8.5")
```

## Join into a single data frame
```{r}
all_rcps <- dplyr::bind_rows(rcp26, rcp45, rcp60, rcp85) # bind all rows together

all_rcps <- all_rcps %>%
  select(Year, rcp, E0_OA0, E1_OA0) %>%
  rename(evolution = E1_OA0, baseline = E0_OA0) %>%
  gather(Model_run, coral, 3:4)

names(all_rcps)
  
```

## Plot using faceting
```{r plot}
ggplot(data = all_rcps, aes(x=Year, y= coral)) + 
geom_line(aes(color = Model_run)) +
facet_wrap(~ rcp) +   # facet by RCP
theme_bw() +          # set theme
xlim(c(2000,2100)) +  # set x limits
labs(x = "Year", y = "Normalized mean global coral cover") 


# show plot
ggsave("Figure2.png", width = 25, height = 12, units = "cm", device = "png") # save plot
```


  
